Fix  DisconnectAsync hangs on Windows and Android after scanning then…
dotnet-bluetooth-le/dotnet-bluetooth-le pull request #735
Opened 2023-08-11 15:02 UTC by TravisRo

… connecting with ConnectToKnownDeviceAsync #734

In the native Windows and Android adapter, it always create a new native `IDevice` instance when using `ConnectToKnownDeviceAsync` if the device has already been discovered via scanning you end up with two `IDevice` instances.  If the user then calls `DisconnectDeviceAsync` on the `IDevice` instance that was discovered via scanning, this issue occurs.

I DID NOT check the other platform adapters so this issue may be present in other platforms.  The solution is easy; just check the `DiscoveredDevicesRegistry` before creating a new `Device` instance.

2023-08-11 18:07 UTC, travis012 commented
Ohh no!  the builder must be broken..

wasn't me.. :)

2023-08-15 19:45 UTC, janusw commented
> Ohh no! the builder must be broken..
> 
> wasn't me.. :)

Yeah, it certainly does not look like you caused it. It happens in another PR as well. Might be due to updated tooling versions on the build host. Will try to look into that ...

2023-08-27 11:02 UTC, janusw commented
Alright, I fixed the CI issues in #737 and rebased this one, so that all build checks succeed now.

2023-08-27 12:00 UTC, janusw requested changes

2023-08-27 13:42 UTC, TravisRo commented
Yeah that sounds good to me.  I can handle that.  I don't have a way to test on iOS and MAC so someone should probably look it over.  I also think we should add our device object to the `DiscoveredDevicesRegistry` if it's not already in there. Provided of-course that `ConnectToKnownDeviceAsync` succeeds.  This will cover us on both ends.

2023-08-27 14:03 UTC, janusw commented
> Yeah that sounds good to me. I can handle that.

Awesome, thanks! :+1:

> I don't have a way to test on iOS and MAC so someone should probably look it over.

I can possibly take care of that part. In any case, if your generic code works well on Android and Windows, I think the probability is quite low that it will cause problems on iOS (given that it is reasonably simple).

> I also think we should add our device object to the `DiscoveredDevicesRegistry` if it's not already in there. Provided of-course that `ConnectToKnownDeviceAsync` succeeds. This will cover us on both ends.

Yes, I think that makes sense.

2023-08-28 01:45 UTC, TravisRo commented
Previous changes reverted and new proposed changes pushed.  Tested on Windows and Android.  I've also updated code to throw a `DeviceConnectionException` as apposed to a generic `Exception` when `ConnectToKnownDeviceNativeAsync` cannot find the device being requested.

2023-08-28 19:13 UTC, janusw approved these changes
LGTM now. Thanks a lot for the contribution!

2023-08-28 19:16 UTC, merged